web、ssh登录失败优化 支持多个ip失败合并推送

diff --git a/root/usr/bin/pushbot/pushbot b/root/usr/bin/pushbot/pushbot
--- a/root/usr/bin/pushbot/pushbot
+++ b/root/usr/bin/pushbot/pushbot
@@ -1,5 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 
+# /usr/bin/pushbot/pushbot
 # 读取设置文件
 function get_config(){
 	while [[ "$*" != "" ]]; do
@@ -19,7 +20,7 @@ function read_config(){
 	"up_timeout" "down_timeout" "timeout_retry_count" "thread_num" "soc_code" "pve_host" "pve_port"\
 	"err_enable" "err_sheep_enable" "err_device_aliases" "network_err_event" "system_time_event" "autoreboot_time" "network_restart_time" "public_ip_event" "public_ip_retry_count" \
 	"jsonpath" "dd_webhook" "we_webhook" "pp_token" "pp_channel" "pp_webhook" "pp_topic_enable" "pp_topic" "fs_webhook" "pushdeer_key" "pushdeer_srv_enable" "pushdeer_srv" "bark_srv_enable" "bark_srv" "bark_token" "bark_sound" "bark_icon" "bark_icon_enable" "bark_level"
-	
+
 	for str_version in "wrtbwmon" "iputils-arping" "curl" "iw"; do
 		eval `echo ${str_version:0:2}"_version"`=`opkg list-installed|grep -w ^${str_version}|awk '{print $3}'` 2>/dev/null
 	done
@@ -46,7 +47,7 @@ function read_config(){
 	[ -z "$timeout_retry_count" ] && timeout_retry_count="2";[ "$timeout_retry_count" -eq "0" ] && timeout_retry_count="1"
 	[ ! -z "$bark_token" ] && [ -z "$bark_srv" ] && bark_srv="https://api.day.app"
 	[ ! -z "$pushdeer_key" ] && [ -z "$pushdeer_srv" ] && pushdeer_srv="https://api2.pushdeer.com"
-	
+
 # 字符串读取
 	str_title_start=`/usr/bin/jq -r '.str_title_start' ${jsonpath}`
 	str_title_end=`/usr/bin/jq -r '.str_title_end' ${jsonpath}`
@@ -66,8 +67,8 @@ function read_config(){
 	table_tab=`/usr/bin/jq -r '.tabletab' ${jsonpath}`
 	( echo "$lite_enable"|grep -q "content" ) && str_title_start="" && str_title_end="" && str_splitline="" && str_linefeed="" && str_tab=""
 }
-	
-	
+
+
 
 # 初始化
 function pushbot_init(){
@@ -81,7 +82,7 @@ function pushbot_init(){
 	deltemp
 	get_syslog
 	add_ip_black
-	
+
 	rm -f ${dir}fd1 ${dir}sheep_usage ${dir}old_sheep_usage ${dir}client_usage_aliases ${dir}old_client_usage_aliases /usr/bin/pushbot/errlog >/dev/null 2>&1
 	[ ! -f "/usr/sbin/wrtbwmon" ] && echo "`date "+%Y-%m-%d %H:%M:%S"` 【！！！】未安装 wrtbwmon ，流量统计不可用" >> ${logfile}
 	[ -z "$ip_version" ] && echo "`date "+%Y-%m-%d %H:%M:%S"` 【！！！】无法获取依赖项 iputils-arping 版本号，请确认插件是否正常运行" >> ${logfile}
@@ -103,7 +104,7 @@ function diy_send(){
 	[ -f ${tempjsonpath} ] && local logrow=$(grep -c "" ${tempjsonpath}) || local logrow="0"
 	[ $logrow -eq "0" ] && echo "`date "+%Y-%m-%d %H:%M:%S"` 【！！！】json 文件生成失败，请检查文件格式" >> ${logfile} && return 1
 	/usr/bin/jq -r '.[]' ${tempjsonpath}|grep "null" && echo "`date "+%Y-%m-%d %H:%M:%S"` 【！！！】参数变量生成失败，请检查设置项 `/usr/bin/jq -r '.' ${tempjsonpath}|grep "null"`" >> ${logfile}
-	
+
 	curl -X POST -H "$content_type" -d "${data}" "${diyurl}"
 }
 
@@ -118,7 +119,7 @@ function down_oui(){
 			cat ${dir}oui.txt|grep "base 16"|grep -i "apple\|aruba\|asus\|autelan\|belkin\|bhu\|buffalo\|cctf\|cisco\|comba\|datang\|dell\|dlink\|dowell\|ericsson\|fast\|feixun\|\
 fiberhome\|fujitsu\|grentech\|h3c\|hisense\|hiwifi\|honghai\|honghao\|hp\|htc\|huawei\|intel\|jinli\|jse\|lenovo\|lg\|liteon\|malata\|meizu\|mercury\|meru\|moto\|netcore\|\
 netgear\|nokia\|omron\|oneplus\|oppo\|philips\|router_unkown\|samsung\|shanzhai\|sony\|start_net\|sunyuanda\|tcl\|tenda\|texas\|tianyu\|tp-link\|ubq\|undefine\|VMware\|\
-utstarcom\|volans\|xerox\|xiaomi\|zdc\|zhongxing\|smartisan" > ${oui_base} && echo "`date "+%Y-%m-%d %H:%M:%S"` 【初始化】设备MAC厂商信息下载成功" >> ${logfile} || echo "`date "+%Y-%m-%d %H:%M:%S"` 【！！！】设备MAC厂商信息下载失败" >> ${logfile} 
+utstarcom\|volans\|xerox\|xiaomi\|zdc\|zhongxing\|smartisan" > ${oui_base} && echo "`date "+%Y-%m-%d %H:%M:%S"` 【初始化】设备MAC厂商信息下载成功" >> ${logfile} || echo "`date "+%Y-%m-%d %H:%M:%S"` 【！！！】设备MAC厂商信息下载失败" >> ${logfile}
 		fi
 		if [ -f ${dir}oui.txt ] && [ "$oui_data" -eq "2" ]; then
 			cat ${dir}oui.txt|grep "base 16" > ${oui_base} && echo "`date "+%Y-%m-%d %H:%M:%S"` 【初始化】设备MAC厂商信息下载成功" >> ${logfile} || echo "`date "+%Y-%m-%d %H:%M:%S"` 【！！！】设备MAC厂商信息下载失败" >> ${logfile}
@@ -734,7 +735,7 @@ function ip_changes(){
 		echo "`date "+%Y-%m-%d %H:%M:%S"` ${disturb_text}路由器已经重启!" >> ${logfile}
 		[ ! -z "$pushbot_ipv4" ] && [ "$pushbot_ipv4" -ne "0" ] && echo "`date "+%Y-%m-%d %H:%M:%S"`  当前IP: ${IPv4}" >> ${logfile}
 		[ ! -z "$pushbot_ipv6" ] && [ "$pushbot_ipv6" -ne "0" ] && echo "`date "+%Y-%m-%d %H:%M:%S"`  当前IPv6: ${IPv6}" >> ${logfile}
-		echo IPv4 $IPv4 > ${dir}ip && echo -e IPv6 $IPv6 >> ${dir}ip	
+		echo IPv4 $IPv4 > ${dir}ip && echo -e IPv6 $IPv6 >> ${dir}ip
 		title="路由器重新启动"
 		content="${content}${str_splitline}${str_title_start}${font_green} 路由器重新启动${font_end}${str_title_end}"
 		[ ! -z "$pushbot_ipv4" ] && [ "$pushbot_ipv4" -ne "0" ] && content="${content}${str_linefeed}${str_tab}当前IP：${IPv4}"
@@ -980,10 +981,10 @@ function login_send(){
 	cat ${dir}login_monitor|grep -i "accepted login"|awk '{print $4" "$NF}' >> ${dir}web_login
 	cat ${dir}login_monitor|grep -i "Password auth succeeded\|Pubkey auth succeeded"|grep -Eo "[0-9]{2}:[0-9]{2}:[0-9]{2}.*[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}"|awk '{print $1" "$NF" "$5}' >> ${dir}ssh_login
 	cat ${dir}login_monitor|grep -i "failed login"|grep -Eo "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}" >> ${dir}web_failed
-	cat ${dir}login_monitor|grep -i "Bad password attempt\|Login attempt for nonexistent user from"|grep -Eo "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}" >> ${dir}ssh_failed
+	cat ${dir}login_monitor|grep -i "Bad password attempt\|Exit before auth from .*: Exited normally\|Failed password"|grep -Eo "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}"  >> ${dir}ssh_failed
 	echo "" > ${dir}login_monitor
 	add_ip_black
-	
+
 	local login_ip_list=`cat ${dir}web_login|awk '{print $2}'|grep -v "^$"|sort -u|head -n1`
 	for login_ip in $login_ip_list; do
 		[ -z "$login_ip" ] && continue
@@ -1031,56 +1032,103 @@ function login_send(){
 	echo "" > ${dir}ssh_login
 	unset login_ip login_ip_list
 
-	local login_ip_list=`cat ${dir}web_failed|awk '{print $1}'|grep -v "^$"|sort -u|head -n1`
-	for login_ip in $login_ip_list; do
-		[ -z "$login_ip" ] && continue
-		echo "$ip_white_list"|grep -w -q "$login_ip" && continue
-		local web_login_sum=`cat ${dir}web_failed|grep -w "${login_ip}"|wc -l`
-		if [ "$web_login_sum" -ge "$login_max_num" ] ;then
-			if [ ! -z "$web_login_failed" ] && [ "$web_login_failed" -eq "1" ]; then
-				if [ -z "$title" ]; then
-					title="${login_ip} 通过 Web 频繁尝试登录"
-					content="${content}${str_splitline}${str_title_start}${font_red} 登录失败来源${font_end}${str_title_end}${str_linefeed}${str_tab}设备 IP： ${str_space}${str_space}${str_space}${str_space}${login_ip}"
-					elif ( echo "$title"|grep -q "频繁尝试登录" ); then
-						title="${login_ip} ${title}"
-						content="${content}${str_splitline}${str_tab}设备 IP： ${str_space}${str_space}${str_space}${str_space}${login_ip}"
-					else
-						title="设备状态变化"
-						content="${content}${str_splitline}${str_title_start}${font_red} 登录失败来源${font_end}${str_title_end}${str_linefeed}${str_tab}设备 IP： ${str_space}${str_space}${str_space}${str_space}${login_ip}"
-				fi
-			fi
-			sed -i "/^${login_ip}$/d" ${dir}web_failed
-			echo "`date "+%Y-%m-%d %H:%M:%S"` 【！！！】设备 ${login_ip} 通过 Web 频繁尝试登录" >> ${logfile}
-			add_ip_black $login_ip
-		fi
-	done
-	unset login_ip
+	web_failed_notify
+	unset login_ip login_ip_list
 
-	local login_ip_list=`cat ${dir}ssh_failed|awk '{print $1}'|grep -v "^$"|sort -u|head -n1`
-	for login_ip in $login_ip_list; do
-		[ -z "$login_ip" ] && continue
-		echo "$ip_white_list"|grep -w -q "$login_ip" && continue
-		local ssh_login_sum=`cat ${dir}ssh_failed|grep -w "${login_ip}"|wc -l`
-		if [ "$ssh_login_sum" -ge "$login_max_num" ] ;then
-			if [ ! -z "$ssh_login_failed" ] && [ "$ssh_login_failed" -eq "1" ]; then
-				if [ -z "$title" ]; then
-					title="${login_ip} 通过 SSH 频繁尝试登录"
-					content="${content}${str_splitline}${str_title_start}${font_red} 登录失败来源${font_end}${str_title_end}${str_linefeed}${str_tab}设备 IP： ${str_space}${str_space}${str_space}${str_space}${login_ip}"
-					elif ( echo "$title"|grep -q "频繁尝试登录" ); then
-						title="${login_ip} ${title}"
-						content="${content}${str_splitline}${str_tab}设备 IP： ${str_space}${str_space}${str_space}${str_space}${login_ip}"
-					else
-						title="设备状态变化"
-						content="${content}${str_splitline}${str_title_start}${font_red} 登录失败来源${font_end}${str_title_end}${str_linefeed}${str_tab}设备 IP： ${str_space}${str_space}${str_space}${str_space}${login_ip}"
-				fi
-			fi
-			sed -i "/^${login_ip}$/d" ${dir}ssh_failed
-			echo "`date "+%Y-%m-%d %H:%M:%S"` 【！！！】设备 ${login_ip} 通过 SSH 频繁尝试登录" >> ${logfile}
-			add_ip_black $login_ip
-		fi
-	done
-	unset login_ip
+	ssh_failed_notify
+	unset login_ip login_ip_list
 
+}
+
+function web_failed_notify() {
+  [ -z "$web_login_failed" ] && return
+  # 统一执行
+  # cat ${dir}login_monitor|grep -i "failed login"|grep -Eo "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}" >> ${dir}web_failed
+
+  get_and_del_login_ip_list "${dir}web_failed" $login_max_num 3
+  if [ "${#error_ip_list[@]}" -ge 1 ]; then
+    local ip_list_string=`printf "%s," "${error_ip_list[@]}"`
+    echo "`date "+%Y-%m-%d %H:%M:%S"` 【！！！】设备 ${ip_list_string} 通过 Web 频繁尝试登录" >> ${logfile}
+    if [ ! -z "$web_login_failed" ] && [ "$web_login_failed" -eq "1" ]; then
+      if [ -z "$title" ]; then
+        title="${ip_list_string} 通过 Web 频繁尝试登录"
+        content="${content}${str_splitline}${str_title_start}${font_red} 登录失败来源${font_end}${str_title_end}${str_linefeed}${str_tab}设备 IP： ${str_space}${str_space}${str_space}${str_space}${ip_list_string}"
+      elif ( echo "$title"|grep -q "频繁尝试登录" ); then
+        title="${ip_list_string} ${title}"
+        content="${content}${str_splitline}${str_tab}设备 IP： ${str_space}${str_space}${str_space}${str_space}${ip_list_string}"
+      else
+        title="设备状态变化"
+        content="${content}${str_splitline}${str_title_start}${font_red} 登录失败来源${font_end}${str_title_end}${str_linefeed}${str_tab}设备 IP： ${str_space}${str_space}${str_space}${str_space}${ip_list_string}"
+      fi
+    fi
+  fi
+  unset error_ip_list
+}
+
+function ssh_failed_notify() {
+  [ -z "$ssh_login_failed" ] && return
+  # 统一执行
+  # cat ${dir}login_monitor|grep -i "Bad password attempt\|Exit before auth from .*: Exited normally\|Failed password"|grep -Eo "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}"  >> ${dir}ssh_failed
+
+  echo "${!login_ip_list[@]}" >>  /tmp/pushbot/pushbot.log
+  ## 统计前三
+  get_and_del_login_ip_list "${dir}ssh_failed" $login_max_num 3
+
+  echo "${!login_ip_list[@]}" >>  /tmp/pushbot/pushbot.log
+
+  if [ "${#error_ip_list[@]}" -ge 1 ]; then
+    local ip_list_string=`printf "%s," "${error_ip_list[@]}"`
+    echo "`date "+%Y-%m-%d %H:%M:%S"` 【！！！】设备 ${ip_list_string} 通过 SSH 频繁尝试登录" >> ${logfile}
+    if [ ! -z "$ssh_login_failed" ] && [ "$ssh_login_failed" -eq "1" ]; then
+      if [ -z "$title" ]; then
+        title="${ip_list_string} 通过 SSH 频繁尝试登录"
+        content="${content}${str_splitline}${str_title_start}${font_red} 登录失败来源${font_end}${str_title_end}${str_linefeed}${str_tab}设备 IP： ${str_space}${str_space}${str_space}${str_space}${ip_list_string}"
+      elif ( echo "$title"|grep -q "频繁尝试登录" ); then
+        title="${ip_list_string} ${title}"
+        content="${content}${str_splitline}${str_tab}设备 IP： ${str_space}${str_space}${str_space}${str_space}${ip_list_string}"
+      else
+        title="设备状态变化"
+        content="${content}${str_splitline}${str_title_start}${font_red} 登录失败来源${font_end}${str_title_end}${str_linefeed}${str_tab}设备 IP： ${str_space}${str_space}${str_space}${str_space}${ip_list_string}"
+      fi
+    fi
+
+  fi
+  unset error_ip_list
+}
+
+function get_and_del_login_ip_list() {
+  ## 通过error_ip_list获取符合要求的ip
+  local login_file=$1
+  local max_num=$2
+  if [ -z "$login_file" ] || [ -z "${max_num}" ]; then
+	  return
+  fi
+
+  local top_n=$3
+  if [ -z "${top_n}" ]; then
+    top_n=1;
+  fi
+
+  # 删除白名单ip
+  if [ -n "$ip_white_list" ]; then
+    while IFS= read -r line; do
+      [ -z "$line" ] && continue
+      sed -i "/^${line}$/d" ${login_file}
+    done <<< "$ip_white_list"
+  fi
+
+  local login_ip_list=`cat ${login_file}|awk '{print $1}'|grep -v "^$"|sort |uniq -c|sort -r|head -n${top_n}`
+  while IFS= read -r line; do
+    [ -z "$line" ] && continue
+    local ip_num=$(echo $line | awk '{print $1}')
+    local login_ip=$(echo $line | awk '{print $2}')
+
+    if [ "$ip_num" -ge "$max_num" ] ;then
+      error_ip_list+=("${login_ip}")
+      sed -i "/^${login_ip}$/d" ${login_file}
+      add_ip_black $login_ip
+    fi
+  done <<< "${login_ip_list}"
 }
 
 # 添加黑名单
@@ -1089,13 +1137,13 @@ function add_ip_black(){
 	[ ! -f "${ip_blacklist_path}" ] && local logrow="0"
 	[ ! -z "$web_login_black" ] && [ "$web_login_black" -eq "0" ] || [ -z "$web_login_black" ] && local logrow="0"
 	ipset flush ip_blacklist >/dev/null 2>&1
-	
+
 	if [ $logrow -le "0" ]; then
 		iptables -D INPUT -m set --match-set ip_blacklist src -j DROP >/dev/null 2>&1
 		ipset destroy ip_blacklist >/dev/null 2>&1
 		return
 	fi
-	
+
 	ipset list ip_blacklist >/dev/null 2>&1 || ipset create ip_blacklist hash:ip timeout ${ip_black_timeout} >/dev/null 2>&1
 	iptables -C INPUT -m set --match-set ip_blacklist src -j DROP >/dev/null 2>&1 || iptables -I INPUT -m set --match-set ip_blacklist src -j DROP >/dev/null 2>&1
 	echo "$1" >> ${ip_blacklist_path}
@@ -1266,7 +1314,7 @@ while [ "$pushbot_enable" -eq "1" ]; do
 		[ "$disturb" -eq "0" ] && diy_send "${title}" "${content}" "${jsonpath}" >/dev/null 2>&1
 		[ $? -eq 1 ] && echo "`date "+%Y-%m-%d %H:%M:%S"` 【！！！】推送失败，请检查网络或设置信息 " >> ${logfile}
 	fi
-	
+
 	while [ -f "${dir}send_enable.lock" ]; do
 		sleep $sleeptime
 	done
